apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-pricing-api.fullname" . }}
  labels:
    {{- include "cloud-pricing-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cloud-pricing-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloud-pricing-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.api.topologySpread.enabled }}
      topologySpreadConstraints:
      - maxSkew: {{ .Values.api.topologySpread.maxSkew }}
        topologyKey: "{{ .Values.api.topologySpread.topologyKey }}"
        whenUnsatisfiable: {{ .Values.api.topologySpread.whenUnsatisfiable }}
        labelSelector:
          matchLabels:
            {{- include "cloud-pricing-api.selectorLabels" . | nindent 12 }}
      {{- end }}
      {{- if .Values.api.extraVolumes }}
      volumes:
      {{- toYaml .Values.api.extraVolumes | nindent 6 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloud-pricing-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.api.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.api.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        {{- with .Values.api.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: {{ .Values.api.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.api.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.api.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: {{ .Values.api.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.api.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.api.readinessProbe.timeoutSeconds }}
          lifecycle:
            {{- if .Values.api.preStopSleepSeconds }}
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep {{ .Values.api.preStopSleepSeconds }}"]
            {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- if .Values.api.extraVolumeMounts }}
          volumeMounts:
          {{- toYaml .Values.api.extraVolumeMounts | nindent 12 }}
          {{- end}}
          env:
            - name: POSTGRES_HOST
              value: {{ include "cloud-pricing-api.postgresql.host" . }}
            - name: POSTGRES_PORT
              value: {{ include "cloud-pricing-api.postgresql.port" . }}
            - name: POSTGRES_DB
              value: {{ include "cloud-pricing-api.postgresql.database" . }}
            - name: POSTGRES_USER
              value: {{ include "cloud-pricing-api.postgresql.user" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloud-pricing-api.postgresql.secretName" . }}
                  key: postgresql-password
            - name: INFRACOST_API_KEY
              valueFrom:
                secretKeyRef:
                  {{- if not .Values.existingSecretAPIKey }}
                  name: {{ include "cloud-pricing-api.fullname" . }}
                  {{- else }}
                  name: {{ .Values.existingSecretAPIKey }}
                  {{- end }}
                  key: infracost-api-key
            {{- if not .Values.api.disableSelfHostedInfracostAPIKey }}
            - name: SELF_HOSTED_INFRACOST_API_KEY
              valueFrom:
                secretKeyRef:
                  {{- if not .Values.api.existingSecretSelfHostedAPIKey }}
                  name: {{ include "cloud-pricing-api.fullname" . }}
                  {{- else }}
                  name: {{ .Values.api.existingSecretSelfHostedAPIKey }}
                  {{- end }}
                  key: self-hosted-infracost-api-key
            {{- end }}
            - name: LOG_LEVEL
              value: {{ .Values.api.logLevel | quote }}
            - name: DISABLE_TELEMETRY
              value: {{ .Values.api.disableTelemetry | quote }}
            {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
