apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-pricing-api.fullname" . }}
  annotations:
    {{- with .Values.secretAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "cloud-pricing-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.api.existingSecretSelfHostedAPIKey }}
  {{- if .Values.api.selfHostedInfracostAPIKey }}
  self-hosted-infracost-api-key: {{ .Values.api.selfHostedInfracostAPIKey | b64enc | quote }}
  {{- else if not .Values.api.disableSelfHostedInfracostAPIKey }}
  self-hosted-infracost-api-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- end }}
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}
  {{- range $key, $value := .Values.extraSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
